TARGETDIR=C:\DCAF

Section Catalog
Begin

  ObjectType=SOFTWARE

  GlobalName=DCAF.DEINSTALL.CMD.REF.1.0

  Description="DCAF V1.03 Remote De-install "

End
 
Section Install                           
Begin                                     
   Program = SA:\img\dcaf\103\DEINSTALL\deindcaf.cmd
   SourceDir= SA:\img\dcaf\103\DEINSTALL
   WorkingDir= SA:\img\dcaf\103\DEINSTALL
End                                       

