/* These are the possible return codes from the LoadBitmapFile() function... */
#define LBF_COULDNT_OPEN_FILE_RC       1
#define LBF_INVALID_BMP_FILE_RC        2
#define LBF_ERROR_CREATING_BMP_RC      3
#define LBF_ERROR_ALLOC_MEM_RC         4
#define LBF_UNKNOWN_BITCOUNT_VALUE_RC  5
#define SBF_UNKNOWN_FORMAT_RC         16
#define SBF_FORMAT_NO_WRITE           17
#define SBF_ERROR_GETTING_BITMAP_INFO 18
#define SBF_FORMAT_MISMATCH           19
#define SBF_NO_MEMORY                 20
#define SBF_NO_COLOR_TABLE            21
#define SBF_ERROR_GETBITS             22
#define SBF_ERROR_WRITE_FORMAT        23
#define SBF_ERROR_OPEN_FILE           24

#define NO_SLIDE_THREAD_RC            30

#define ABOUTBOX    20
#define HELPBOX     21

#define ID_WINDOW   256

#define ID_BITMAP   111

#define ID_FILE_MENU              50
#define ID_LOADFILE               51
#define ID_SAVEFILE               52
#define ID_SAVERLEFILE            71
#define ID_LOADSLD                53
#define ID_ABOUT                  54

#define ID_DRAW_MENU              55
#define ID_SCALE_WHILE_DRAW       56
#define ID_CLEAR_BITMAP           57
#define ID_PALETTE_MANAGEMENT     58
#define ID_KEEP_PROPORTION        59
#define ID_FRAME_EMPTY            70

#define ID_SLIDE_MENU             60
#define ID_RESTART                61
#define ID_PAUSE                  62
#define ID_TERMINATE              63
#define ID_FORWARD                64
#define ID_REVERSE                65

#define ID_EXIT_MENU              66
#define ID_EXIT                   67
#define ID_RESUME                 68

#define ID_HELP                   69


#define ID_NULL     -1
