# SCCSID = @(#)makefile 13.7 93/07/26
#**************************************************************************
#
# MAKE file for RIFF compound file sample program
#
# Assumes that the environment is set up for development.  Specifically,
# the compiler, linker, rc and ipfc  should be in the path.  Also, the
# environment variables for the tools must be properly set, e.g. LIB,
# INCLUDE, IPFC. This should all be taken care of automatically by
# installing the OS/2 Toolkit and the MMPM/2 Toolkit.
#
# Copyright (C) IBM 1993
#**************************************************************************

CC          = icc
LINK        = link386

BASELIBS    = DDE4MBS.LIB OS2386.LIB MMPM2.LIB

DEBUG      = /Ti+ /O-
COMPILE = /G3s /C+ /W3 /Ss+ /Gd- /Ms /Gm+ /DINCL_32

#
# Compilation Switches
#
#     /G3s           : Generate 386 code with no stack checking.
#     /C+            : Compile only one module.
#     /W3            : Warning level.
#     /Ss+           : Allow Double Slash comments
#     /Gd-           : Link to static C libraries.
#     /Gm+           : Use multithreaded libraries.
#     /DINCL_32      : Use IBM code.
#     /Ti+           : Generate debugging code.
#     /O-            : Turn optimization off.
#

CFLAGS = $(COMPILE)

LFLAGS  = /map /nod /noe
DBLFLAG = /CO

#
# Link Switches
#
#    /map     : Creates a listing file containing all pulbic symbols.
#    /nod     : Causes all default libraries to be ignored.
#    /noe     : The linker will not search the extended dictionary.
#    /CO      : Debug
#

all: riffsamp.exe riffsamp.hlp

riffsamp.exe : riffsamp.obj riffsamp.def riffsamp.res
 $(LINK) riffsamp.obj, riffsamp, $(LFLAGS) /ST:36000, $(BASELIBS), riffsamp.def
  rc riffsamp.res


riffsamp.obj : riffsamp.c riffsamp.h
  $(CC) $(CFLAGS) $(DEBUG) riffsamp.c


riffsamp.res : riffsamp.rc riffsamp.dlg riffsamp.h riffsamp.ico
  rc -r riffsamp.rc

riffsamp.hlp: $*.ipf
  ipfc $*.ipf
