
/*************************************************************************
 * File Name    :  riffsamp.h
 *
 * Description  :  This file contains the definitions used by the RIFF
 *                 Compound File Sample Program.  The definitions are for all
 *                 Dialogs, string lengths, Resource Id's.
 *
 * Concepts     :  n/a
 *
 * MMPM/2 API's :  n/a
 *
 * Required
 *    Files     :  None.
 *
 *
 * Copyright (C) IBM 1993
 *************************************************************************/

#define ID_MESSAGE_BOX                1
#define ID_TEXT_FILE_TOC            100
#define ID_LB_FILE_TOC              101
#define ID_TEXT_ADD_FILE            102
#define ID_LB_ADD_FILE              103
#define ID_PB_ADD                   104
#define ID_PB_DEL                   105
#define ID_PB_PLAY                  106
#define ID_PB_COMPACT               107

#define ID_ICON                     108
#define ID_HELP                     109
#define ID_SUBTABLE_MESSAGEBOX      110
#define ID_DLG_MAIN                 111


#define ID_RIFFSAMP_HELPTABLE      1042
#define ID_RIFFSAMP_DIALOG_BOX     1043


/* Id's for the Resources defined in the riffsamp.rc file */
#define    IDS_MAIN_WINDOW_TITLE                1
#define    IDS_HELP_CREATION_ERROR              2
#define    IDS_HELP_WINDOW_TITLE                3
#define    IDS_ERROR_TITLE                      4
#define    IDS_CANNOT_GET_MEMORY                5
#define    IDS_CANT_PROCESS_MESSAGE             6
#define    IDS_DEFAULT_SIZE                     7
#define    IDS_NO_WAVE_FILES                    8
#define    IDS_NO_FILES_SELECTED                9
#define    IDS_RIFF_CREATION_ERROR              10
#define    IDS_COULD_NOT_OPEN_WAVE              11
#define    IDS_FILE_NOT_FOUND                   12
#define    IDS_NO_CTOC_ENTRIES_SELECTED         13
#define    IDS_ENTRY_ALREADY_EXISTS             14



