/***************************************************************************/
/* XPRMINFO.H    XPG4 Primer for OS/2 WARP - V1.0       11/15/95           */
/*               Product Information dialog resource definitions.          */
/***************************************************************************/
#define DID_ABOUT      9000
#define AB_BID_LOGO    9001
#define AB_STX_COPY1   9002
#define AB_STX_COPY2   9003
#define AB_STX_COPY3   9004
