/*******************************************************************************
**                           I B M    C O N F I D E N T I A L                 **
********************************************************************************
**  Module Name:  EULPMPRT.H                                                  **
**                                                                            */
#define ID_FILENAME   263
#define ID_DESKTOP    260
#define ID_ACTIVE     259
#define ID_FILE       258
#define ID_PRINT      257
#define ID_PMPRT      256
#define NAMELENGTH    8
/*******************************************************************************/
#define PRTHOOK "PMPRTD"
