The Redbooks for LAN Systems are packages of Sample Code for diffent LAN Systems products.

The different component Redbooks are:
   GG24-4043: Sample Code for LAN Server
   GG24-4090: Sample Code for DCE
   GG24-4357: Sample Code for SOMobjects
   GG24-4387: Sample Code for LAN Manager Migration
   GG24-4388: Sample Code for NetWare Migration
   GG24-4479: Sample Code for SOM-Object Management Utilities for DSOM
   SG24-4673: OpenDoc: An Introduction to Part Development
