/*---------------------------------------------------------------------------+
|  System and C language includes                                            |
+---------------------------------------------------------------------------*/
#define INCL_BASE                    /* Defines to get the right OS2 include*/
#define INCL_WIN
#include <OS2.h>
#include <process.h>
/*---------------------------------------------------------------------------+
|  Dialog defines                                                            |
+---------------------------------------------------------------------------*/
#define ID_NULL       -1
#define ID_CHARPLAY   1262
#define MOUSE_PLAY    1261
#define CHAR_PLAY     1260
#define DLG_PLAY      1259
#define EF_Y          1258
#define EF_X          1257
