#UNIXLIKE Development makefile
# Each program includes (or will soon) a file from \unixlike\rel31\src\include
# Make sure this path is part of the INCLUDE environment variable
# 05.03.93: modified for IBM C-SET/2 make

# NOTE:  the more program is not being compiled for 32 bit, nor is ps

CDFLAGS = /c /Gd- /Sm /Re /Ss /Ms /O- /Ti /Gm- /Q+ /I\unixlike\rel31\src\include
CFLAGS  = /c /Gd- /Sm /Re /Ss /Ms /O+    /Gm- /Q+ /I\unixlike\rel31\src\include
CMFLAGS = /c /Gd- /Sm /Re /Ss /Ms /O+    /Gm+ /Q+ /i\unixlike\rel31\src\include
COFLAGS = /c /Gd- /Sm /Re /Ss /Ms /O+    /Gm- /Q+ /I\unixlike\rel31\src\include
LDFLAGS = /DEBUG /ALIGN:32 /EXEPACK /M /NOI
LFLAGS  =        /ALIGN:32 /EXEPACK /M /NOI

# MS C6.0: CFLAGS = -c -AL -G2s -W3 -I\unixlike\rel31\src\include
# MS C6.0: CDFLAGS = -c -AL -G2s -W3 -I\unixlike\rel31\src\include -Zi -Od
# MS C6.0: COFLAGS = -c -AL -G2s -W3 -Ozax -Gr -I\unixlike\rel31\src\include
# MS C6.0: LFLAGS =
# MS C6.0: LDFLAGS = /CO

B = \unixlike\bin
F = \unixlike\util\fmf
G = \unixlike\util\getopt
GU= \unixlike\util\greputil
M = \unixlike\util\myerror
MF =\unixlike\mapfiles
MP= \unixlike\util\makepath
P = \unixlike\util\getopt
S = \unixlike\src
SL =\unixlike\util\sleep
#Z =\unixlike\src\more

COMPOBJS = $S\compress\compress.obj+$S\compress\comprutl.obj

$B\compress.exe :  $S\compress\compress.obj $S\compress\comprutl.obj          \
                   $S\compress\compress.def
         link386 $(LDFLAGS) $(COMPOBJS),$B\compress.exe,NUL,,$S\compress\compress.def;

$S\compress\compress.obj : $S\compress\compress.c
         icc $(CDFLAGS) -DOS2 /Fo$S\compress\compress.obj $S\compress\compress.c

$S\compress\comprutl.obj : $S\compress\comprutl.c
         icc $(CDFLAGS) /Fo$S\compress\comprutl.obj $S\compress\comprutl.c

