# IBM Developer's Workframe/2 Make File Creation run at 10:36:10 on 03/12/93

# Make File Creation run in directory:
#   F:\SWITCH;

# Assumed INCLUDE environment variable path:
#   E:\IBMC\INCLUDE;
#   C:\TOOLKT20\C\OS2H;
#   C:\TOOLKT20\ASM\OS2INC;
#   I:\TOOLKT20\C\OS2H;
#   I:\TOOLKT20\ASM\OS2INC;


hotk.RES:  hotk.RC  \
#  {.;$(INCLUDE)}OS2.H  \
   {.;$(INCLUDE)}HOTK.H  \
   HOTK.ICO  \
   MAKEFILE

hotk.OBJ:  hotk.C  \
#  {$(INCLUDE);}os2.h  \
#  {$(INCLUDE);}stdlib.h  \
#  {$(INCLUDE);}string.h  \
#  {$(INCLUDE);}stdio.h  \
#  {$(INCLUDE);}ctype.h  \
#  {$(INCLUDE);}conio.h  \
#  {$(INCLUDE);}dos.h  \
   {.;$(INCLUDE);}hotk.h  \
   MAKEFILE
