/* ******************************************************************** *  
 * Copyright International Business Machines Corporation 1995, 1996     *
 * DISCLAIMER OF WARRANTIES.                                            *  
 * The following [enclosed] code is sample code created by IBM          *  
 * Corporation. This sample code is not part of any standard or IBM     *  
 * product and is provided to you solely for the purpose of assisting   *  
 * you in the development of your applications.  The code is provided   *  
 * "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT  *  
 * NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS *  
 * FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF   *  
 * THIS CODE.  IBM shall not be liable for any damages arising out of   *  
 * your use of the sample code, even if they have been advised of the   *  
 * possibility of such damages.                                         *  
 *                                                                      *  
 * DISTRIBUTION.                                                        *  
 * This sample code can be freely distributed, copied, altered, and     *  
 * incorporated into other software, provided that it bears the above   *  
 * Copyright notice and DISCLAIMER intact.                              *  
 * -------------------------------------------------------------------- *  
 * This file is part of the source for OpenDoc parts document in:       *
 *  IBM International Technical Support Organization Bulletin (Redbook) *  
 *  "OpenDoc : An Introduction to Part Development" (SG24-4673)         *
 *                                                                      *
 * ******************************************************************** *  
 */   
#ifndef _KPNOTERC_
#define _KPNOTERC_

#define KP_COLORS 100

#define IDMA_COLOR_BASE         MENUID_ACTIVEPART_USER+550
#define IDMA_COLOR_GRAY          IDMA_COLOR_BASE+1
#define IDMA_COLOR_RED           IDMA_COLOR_BASE+2
#define IDMA_COLOR_GREEN         IDMA_COLOR_BASE+3
#define IDMA_COLOR_YELLOW        IDMA_COLOR_BASE+4
#define IDMA_COLOR_BLUE          IDMA_COLOR_BASE+5
#define IDMA_COLOR_MAGENTA       IDMA_COLOR_BASE+6
#define IDMA_COLOR_CYAN          IDMA_COLOR_BASE+7
#define IDMA_COLOR_BLACK         IDMA_COLOR_BASE+8

#define ID_ENTRYDATA             IDMA_COLOR_BASE+20
#define ID_CHECKBOX              IDMA_COLOR_BASE+21

#endif
