# IBM Developer's Workframe/2 Make File Creation run at 11:12:33 on 05/25/93

# Make File Creation run in directory:
#   I:\SIMPLE;

# Assumed INCLUDE environment variable path:
#   E:\IBMC\INCLUDE;
#   C:\TOOLKT20\C\OS2H;
#   C:\TOOLKT20\ASM\OS2INC;
#   I:\TOOLKT20\C\OS2H;
#   I:\TOOLKT20\ASM\OS2INC;


SIMPLE.OBJ:  SIMPLE.C  \
#  {$(INCLUDE);}os2.h  \
#  {$(INCLUDE);}stdio.h  \
#  {$(INCLUDE);}string.h  \
   MAKEFILE
