/***************************************************************************/
/* XPRMRES.H     XPG4 Primer for OS/2 WARP - V1.0                          */
/*               Constants definitions for resource files.                 */
/*               Initial:  09/26/95  Y. Kimura                             */
/***************************************************************************/
#define PID_HELP        9999

#define BID_MAIN        1900
#define BID_ABOUT       9010

#define WID_MAIN        1000
#define MID_ORDER       1100
#define MID_NEWORDER    1101
#define MID_FIND        1102
#define MID_CUST        1200
#define MID_NEWCUST     1201
#define MID_FINDCUST    1202
#define VID_QUITPROG    1299

#define MID_HELP            1301
#define MID_HELPINDEX       1302
#define MID_HELPKEYS        1303
#define MID_HELPFORHELP     1304
#define MID_HELPABOUT       1305

#define DID_LOGIN       2000
#define LI_STX_EMPNUM   2001
#define LI_EF_EMPNUM    2002

#define DID_ORDERENTRY  3000
#define OE_STX_ORDERNUM 3010
#define OE_STX_ORDERDATE 3011
#define OE_STX_ORDERTIME 3012
#define OE_STX_CUSTNUM  3013
#define OE_STX_CUSTNAME 3014
#define OE_STX_ORDERS   3015
#define OE_STX_QTY      3016
#define OE_STX_SUBTOTAL 3017
#define OE_STX_TOTAL    3018
#define OE_EF_ORDERNUM  3020
#define OE_EF_ORDERDATE 3021
#define OE_EF_ORDERTIME 3022
#define OE_EF_CUSTNUM   3023
#define OE_CB_CUSTNAME  3024
#define OE_EF_ORDER1    3025
#define OE_EF_ORDER2    3026
#define OE_EF_ORDER3    3027
#define OE_EF_QTY1      3028
#define OE_EF_QTY2      3029
#define OE_EF_QTY3      3030
#define OE_EF_SUBSUM1   3031
#define OE_EF_SUBSUM2   3032
#define OE_EF_SUBSUM3   3033
#define OE_EF_TOTAL_QTY 3034
#define OE_EF_SUM       3035
#define OE_LI_PRODUCTS  3040

#define DID_QRYORDR     4000
#define QO_STX_KEY      4001
#define QO_EF_KEY       4002
#define QO_GB_CATEGORY  4010
#define QO_PB_DATE      4011
#define QO_PB_NUMBER    4012

#define DID_CUSTINFO    5000
#define CI_STX_CUSTNAME 5010
#define CI_STX_CUSTADDR 5011
#define CI_STX_CUSTTEL  5012
#define CI_EF_NAME      5020
#define CI_ML_CUSTADDR  5021
#define CI_EF_CUSTTEL   5022

#define DID_QRYCUST     6000
#define QC_STX_KEY      6001
#define QC_EF_CUSTKEY   6002
#define QC_GB_CATEGORY  6010
#define QC_PB_CUSTNUM   6011
#define QC_PB_CUSTNAME  6012
#define QC_PB_TELNUM    6013

#define WID_VIEWORDER   7000
#define VO_PB_NEXT      7010
#define VO_PB_PREV      7011
#define MID_OPTION      7100
#define MID_FONT        7101
#define WID_SUBWINDOW   7200

#define DID_CUSTLIST    8000
#define LI_CUSTLIST     8001

#define DID_ABOUT       9000
#define ID_AB_BITMAP    9001

#define MAX_MSG_NUM            64
#define MAX_MSG_LEN            80
#define NUM_OF_CODESET          5


#define IDS_MAIN_TITLE           0
#define IDS_INFO_CAPTION         1
#define IDS_WARNING_CAPTION      2
#define IDS_ERROR_CAPTION        3
#define IDS_INFO_1               4
#define IDS_WARNING_1            5
#define IDS_WARNING_2            6
#define IDS_WARNING_3            7
#define IDS_WARNING_4            8
#define IDS_WARNING_5            9
#define IDS_WARNING_6            10
#define IDS_WARNING_7            11
#define IDS_ERROR_1              12
#define IDS_ERROR_2              13
#define IDS_ERROR_3              14
#define IDS_ERROR_4              15
#define IDS_ERROR_5              16
#define IDS_ERROR_6              17
#define IDS_ERROR_7              18
#define IDS_ERROR_8              19
#define IDS_VO_TITLE             20
#define IDS_VO_NEXT              21
#define IDS_VO_PREV              22
#define IDS_VO_CANCEL            23
#define IDS_VO_DATE              24
#define IDS_VO_CUSTNUM           25
#define IDS_VO_CUSTNAME          26
#define IDS_VO_PRODNAME          27
#define IDS_VO_UNITPRICE         28
#define IDS_VO_QTY               29
#define IDS_VO_SUB               30
#define IDS_VO_TOTQTY            31
#define IDS_VO_TOTPRICE          32
#define IDS_VO_PREVIEW           33
#define IDS_HELP_TITLE           34
#define IDS_ABOUT_TITLE          35
#define IDS_ABOUT_COPY1          36
#define IDS_ABOUT_COPY2          37
#define IDS_ABOUT_COPY3          38
#define IDS_ABOUT_OK             39
