/***************************************************************************/
/* XPRMHELP.H    XPG4 Primer for OS/2 WARP - V1.0                          */
/*               Constants definitions for Help Tables.                    */
/*               Initial:  09/26/95  Y. Kimura                             */
/***************************************************************************/
#define  HID_MAIN             17000
#define  HELP_MAIN            17001

#define  HELP_SUB_MAIN        17100
#define  HELP_MID_ORDER       17101
#define  HELP_MID_NEWORDER    17102
#define  HELP_MID_FIND        17103
#define  HELP_MID_CUST        17104
#define  HELP_MID_NEWCUST     17105
#define  HELP_MID_FINDCUST    17106

#define  HELP_HELP            17110
#define  HELP_HELPINDEX       17111
#define  HELP_HELPKEYS        17112
#define  HELP_HELPFORHELP     17113
#define  HELP_HELPABOUT       17114

#define  HELP_HELPKEYSPANEL   17120

#define  HELP_SUB_LOGIN       17200
#define  HELP_LOGIN           17201
#define  HELP_LI_EMPNUM       17202

#define  HELP_SUB_ORDERENTRY  17300
#define  HELP_ORDERENTRY      17301
#define  HELP_OE_CUSTNAME     17302
#define  HELP_OE_QTY          17303
#define  HELP_LI_PRODUCTS     17304

#define  HELP_SUB_QRYORDR     17400
#define  HELP_QRYORDR         17401
#define  HELP_QO_KEY          17402
#define  HELP_QO_DATE         17403
#define  HELP_QO_NUMBER       17404

#define  HELP_SUB_VIEWORDER   17500
#define  HELP_VIEWORDER       17501
#define  HELP_MID_OPTION      17502
#define  HELP_MID_FONT        17503

#define  HELP_SUB_CUSTINFO    17600
#define  HELP_CUSTINFO        17601
#define  HELP_CI_NAME         17602
#define  HELP_CI_CUSTADDR     17603
#define  HELP_CI_CUSTTEL      17604

#define  HELP_SUB_QRYCUST     17700
#define  HELP_QRYCUST         17701
#define  HELP_QC_CUSTKEY      17702
#define  HELP_QC_CUSTNUM      17703
#define  HELP_QC_CUSTNAME     17704
#define  HELP_QC_TELNUM       17705

#define  HELP_SUB_CUSTLIST    17800
#define  HELP_CUSTLIST        17801

