
#define  RGB_HPS(hps)     GpiCreateLogColorTable(hps,0,LCOLF_RGB,0,0,NULL)

#define  CLR_ARRAY                "CLR_ARRAY"
#define  ID_RGBDLG                4108

#define  IDD_RGB_ARRAY            20
#define  IDD_RGB_CURCLR           21
#define  IDD_RGB_EDITCLR          22
#define  IDD_RGB_CLR_R            23
#define  IDD_RGB_CLR_G            24
#define  IDD_RGB_CLR_B            25
#define  IDD_RGB_HELP             26
#define  IDD_RGB_CLRCHANGE        27
#define  IDD_RGB_PALETTE          28
#define  IDD_RGB_CLRCHANGE2       29

