/*** OS/2 Application Primer "MISC Sample Secondary Window Procedures"*/
/*                                                                    */
/* Program name : MISCRSC.H                                           */
/* Version : 2.1 (12/24/93)                                           */
/*                                                                    */
/*    << This sample program is only for DBCS OS/2 V2.1. >>           */
/*                                                                    */
/*    Resource ID definitions of Sample Miscellenaeus program.        */
/*                                                                    */
/**********************************************************************/

#define WID_MAIN      1000

#define MID_FILE      1010
#define MID_CONV      1011
#define MID_EDITOR    1012
#define MID_WORD      1013
#define MID_SEP       1018
#define MID_EXIT      1019

#define DID_CONV      3000
#define PB_CAN        3051
#define PB_EXE        3050
#define STX_ENTERSTR  3062
#define STX_HEX       3063
#define STX_HOST      3054
#define STX_PC0       3052
#define STX_TEXT      3070
#define STX_TRANS     3065
#define STX_WINCP     3064

#define CB_HCODE      3055
#define EF_HCTEXT     3056
#define EF_HOSTTRAN   3069
#define EF_HOSTWIN    3068
#define EF_PC         3067
#define EF_PCCP       3053
#define EF_STRING     3066

#define WID_EDITOR    4000
#define MID_EDITOPT   4020
#define MID_ONSPOT    4021

#define DID_WORD      5000
#define MID_WDBREAK   5010
#define MID_BREAKON   5011
#define STX_SAMPLE    5021

#define IDS_MAINTEXT1 6000
#define IDS_MAINTEXT2 6001
#define IDS_MAINTEXT3 6002
#define IDS_TEXTENJOY 6009

#define IDS_TEXT1     6010
#define IDS_TEXT2     6011
#define IDS_TEXT3     6012
#define IDS_TEXT4     6013
#define IDS_TEXT5     6014

#define ERR_TITLE     6020
#define ERR_CTRYCODE  6021
#define ERR_FILE      6022
#define ERR_CPFLAG    6023
