/* ********************************************************************** */
/*                                                                        */
/*    ToolBar.h                                                           */
/*                                                                        */
/*                                                                        */
/* ********************************************************************** */

#define  ID_MAIN_WIN     10

#define   MID_MENUBAR    100
#define   MID_MENU1      101
#define   MID_SUB11      102
#define   MID_MENU2      103
#define   MID_SUB21      104
#define   MID_SUB22      105
#define   MID_MENU3      106
#define   MID_SUB31      106
#define   MID_SUB32      107
#define   MID_SUB33      108

#define   MID_TOOLBAR    200
#define   MID_TB_1       201
#define   MID_TB_2       202
#define   MID_TB_3       203
#define   MID_TB_4       204
#define   MID_TB_5       205
#define   MID_TB_6       206
#define   MID_TB_7       207
#define   MID_TB_8       208
#define   MID_TB_9       209
#define   MID_TB_10      210
