/*

gbmv2.h - Resource and Window ID's

*/

#define	VERSION			100

/* Resources. */

#define	RID_GBMV2		1000
#define	RID_SELECT1		1001
#define	RID_SELECT2		1002
#define	RID_HELP_TABLE		1003
#define	RID_DLG_ABOUT		1004
#define	RID_DLG_COLOUR		1005
#define	RID_DLG_MAP		1006
#define	RID_DLG_RESIZE		1007

/* Menu selections. */

#define	MID_FILE		1100
#define	MID_NEW			1101
#define	MID_OPEN		1102
#define	MID_SAVE		1103
#define	MID_SAVE_AS		1104
#define	MID_EXPORT_MET		1105
#define	MID_PRINT		1106
#define	MID_SNAPSHOT		1107
#define	MID_EDIT		1108
#define	MID_UNDO		1109
#define	MID_SELECT		1110
#define	MID_DESELECT		1111
#define	MID_COPY		1112
#define	MID_PASTE		1113
#define	MID_BITMAP		1114
#define	MID_REF_HORZ		1115
#define	MID_REF_VERT		1116
#define	MID_ROT_90		1117
#define	MID_ROT_180		1118
#define	MID_ROT_270		1119
#define	MID_TRANSPOSE		1120
#define	MID_CROP		1121
#define	MID_COLOUR		1122
#define	MID_MAP			1123
#define	MID_RESIZE		1124
#define	MID_VIEW		1125
#define	MID_VIEW_NULL		1126
#define	MID_VIEW_HALFTONE	1127
#define	MID_VIEW_ERRDIFF	1128
#define	MID_HELP		1129
#define	MID_HELP_FOR_HELP	1130
#define	MID_ABOUT		1131
#define	MID_EXIT		1132 /* Not actually on menu */

/* Dialog control ID's. */

#define	DID_HELP		1200
#define	DID_MAPPING		1201
#define	DID_I_TO_L		1202
#define	DID_I_TO_P		1203
#define	DID_L_TO_I		1204
#define	DID_L_TO_P		1205
#define	DID_P_TO_I		1206
#define	DID_P_TO_L		1207
#define	DID_PARAMS		1208
#define	DID_GAMMA_TEXT		1209
#define	DID_GAMMA		1210
#define	DID_SHELF_TEXT		1211
#define	DID_SHELF		1212

#define	DID_MAP_TO		1220
#define	DID_MAP_BW		1221
#define	DID_MAP_8		1222
#define	DID_MAP_VGA		1223
#define	DID_MAP_4G		1224
#define	DID_MAP_784		1225
#define	DID_MAP_666		1226
#define	DID_MAP_8G		1227
#define	DID_MAP_TRIPEL		1228
#define	DID_MAP_RGB		1229
#define	DID_MAP_FREQ		1230
#define	DID_MAP_MCUT		1231
#define	DID_VALUES		1232
#define	DID_R_TEXT		1233
#define	DID_R			1234
#define	DID_G_TEXT		1235
#define	DID_G			1236
#define	DID_B_TEXT		1237
#define	DID_B			1238
#define	DID_N_TEXT		1239
#define	DID_N			1240
#define	DID_HOW			1241
#define	DID_NEAREST		1242
#define	DID_HALFTONE		1243
#define	DID_ERRDIFF		1244

#define	DID_CURRENTLY		1250
#define	DID_WIDTH_TEXT		1251
#define	DID_WIDTH		1252
#define	DID_WIDTH_MUL		1253
#define	DID_WIDTH_DIV		1254
#define	DID_WIDTH_MATCH		1255
#define	DID_HEIGHT_TEXT		1256
#define	DID_HEIGHT		1257
#define	DID_HEIGHT_MUL		1258
#define	DID_HEIGHT_DIV		1259
#define	DID_HEIGHT_MATCH	1260
#define	DID_MUL_TEXT		1261
#define	DID_MUL			1262

#define	DID_ICON		1270
#define	DID_TITLE_TEXT		1271
#define	DID_VERSION_TEXT	1272
#define	DID_AUTHOR_TEXT		1273

/* Window ID's */

#define WID_SCROLL 		1280
#define	WID_BITMAP		1281
