#
# Simple bitmap viewer II
#

GBM =		\ak\gbm\gbm
GBMDLG =	\ak\gbm\gbmdlg
SCROLL =	\ak\controls\scroll

.SUFFIXES:	.c .obj

CFLAGS =	/C+ /W3 /I$(SCROLL) /I$(GBM) /I$(GBMDLG) /G4 /Gd-e+m+ /Q+ /Wpro /O+
LFLAGS =	/BATCH /NOLOGO /ALIGN:4 /BASE:0x10000 /NOI

.c.obj:
		icc $(CFLAGS) $*.c

#

all:		gbmv2.exe gbmv2.hlp

OBJS =		model.obj bmputils.obj help.obj gbmv2.obj

LIBS =		$(SCROLL)\scroll.lib \
		$(GBM)\gbm.lib \
		$(GBM)\gbmtrunc.lib $(GBM)\gbmerr.lib $(GBM)\gbmht.lib \
		$(GBM)\gbmhist.lib $(GBM)\gbmmcut.lib \
		$(GBM)\gbmmir.lib $(GBM)\gbmrect.lib $(GBM)\gbmscale.lib \
		$(GBMDLG)\gbmdlg.lib

gbmv2.exe:	$(OBJS) $(LIBS) gbmv2.def gbmv2.res
		link386 $(LFLAGS) $(OBJS),$@,nul,$(LIBS:.lib=),gbmv2.def
		rc gbmv2.res $@

model.obj:	model.c model.h \
		$(GBM)\gbm.h \
		$(GBM)\gbmtrunc.h $(GBM)\gbmerr.h $(GBM)\gbmht.h \
		$(GBM)\gbmhist.h $(GBM)\gbmmcut.h \
		$(GBM)\gbmmir.h $(GBM)\gbmrect.h $(GBM)\gbmscale.h

bmputils.obj:	bmputils.c bmputils.h

help.obj:	help.c gbmv2hlp.h

gbmv2.obj:	gbmv2.c gbmv2.h model.h bmputils.h help.h \
		$(SCROLL)\scroll.h \
		$(GBM)\gbm.h \
		$(GBMDLG)\gbmdlg.h $(GBMDLG)\gbmdlgrc.h

gbmv2.res:	gbmv2.rc gbmv2.ico $(GBMDLG)\gbmdlgrc.h gbmv2.h gbmv2hlp.h
		(set INCLUDE=$(GBMDLG);$(INCLUDE) && rc -r gbmv2.rc)

gbmv2.hlp:	gbmv2.scr gbmv2hlp.h $(GBMDLG)\gbmdlgrc.h $(GBMDLG)\gbmdlg.scr
		(set INCLUDE=$(GBMDLG);$(INCLUDE) && ipfcprep gbmv2.scr gbmv2.ipf)
		ipfc gbmv2.ipf /country=044 /codepage=437 /language=ENG /X /W2

#

clean:
		-del *.obj *.res *.ipf 2> nul

install:
		copy *.exe d:\gbm
		copy *.hlp d:\gbm
