#****************************************************************************
#
#  Work Place Shell Sample makefile
#
#  This makefile builds the three classes: DRAGEXAM, DRAGFOLD and MYFOLDER
#
#  Note: edit the environment/paths for your development environment
#
#  Copyright (C) 1993 IBM Corporation
#
#      DISCLAIMER OF WARRANTIES.  The following [enclosed] code is
#      sample code created by IBM Corporation. This sample code is not
#      part of any standard or IBM product and is provided to you solely
#      for  the purpose of assisting you in the development of your
#      applications.  The code is provided "AS IS", without
#      warranty of any kind.  IBM shall not be liable for any damages
#      arising out of your use of the sample code, even if they have been
#      advised of the possibility of such damages.                                                    *
#
#****************************************************************************

!if [set INCLUDE=d:\som\include;d:\ibmcpp\include;d:\wpshidl\h;d:\toolkt21\c\os2h;.;] || \
    [set LIB=d:\som\lib;d:\ibmcpp\lib;d:\toolkt21\os2lib;] || \
    [set SMINCLUDE=d:\som\include;d:\wpshidl\idl;d:\toolkt21\sc;.;] || \
    [set SMTMP=%TMP%] || \
    [set PATH=d:\som\bin;d:\ibmcpp\bin;d:\toolkt21\os2bin;] || \
    [set DPATH=d:\ibmcpp\locale;d:\ibmcpp\help;] || \
    [set HELP=d:\ibmcpp\help;]
!endif

SCFLAGS = -S128000 -C128000 -mnoint

all: dragexam.dll dragfold.dll myfolder.dll

dragexam.dll: dragexam.obj dragexam.c dragexam.idl
   icc -q -Ss -Ge- -Rn -B"/map /noe" dragexam.DEF SOMTK.LIB dragexam.c
   mapsym dragexam

dragfold.dll: dragfold.obj dragfold.idl dragfold.c
   icc -q -Ss -Ge- -Rn -B"/map /noe" dragfold.DEF SOMTK.LIB dragfold.c
   mapsym dragfold

myfolder.dll: myfolder.obj myfolder.idl myfolder.c myfolder.rc
   icc -q -Ss -Ge- -Rn -B"/map /noe" myfolder.DEF SOMTK.LIB  myfolder.c
   rc myfolder.rc myfolder.dll
   mapsym myfolder


dragexam.obj: dragexam.idl
   sc $(SCFLAGS) -maddstar -r -s "c;ih;h;def" $(@B).idl

dragfold.obj: dragfold.idl
   sc $(SCFLAGS) -maddstar -r -s "c;ih;h;def" $(@B).idl

myfolder.obj: myfolder.idl
   sc $(SCFLAGS) -maddstar -r -s "c;ih;h;def" $(@B).idl


